version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: sphinx-autoapi
    versions:
    - 1.8.0
  - dependency-name: marshmallow
    versions:
    - 3.11.0
  - dependency-name: sphinx
    versions:
    - 3.5.0
    - 3.5.1
    - 3.5.2
