version = 1

# Glob pattern of the test files
test_patterns = [
  "tests/**",
  "test_*.py"
]

[[analyzers]]
name = "python"
enabled = true

dependency_file_paths = [
  "poetry.lock",
  "pyproject.toml"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
