TASK_ENDPOINT = "labthing_task"
TASK_LIST_ENDPOINT = "labthing_task_list"
ACTION_ENDPOINT = "labthing_action"
ACTION_LIST_ENDPOINT = "labthing_task_action"
EXTENSION_LIST_ENDPOINT = "labthing_extension_list"
EXTENSION_NAME = "flask-labthings"
LOG_EVENT_ENDPOINT = "logging"
