"""Test OpenAPI spec generation

This file tests the OpenAPI spec generated by LabThings.
NB in order to avoid duplicating the examples, OpenAPI spec validation is also
done in test_td.py.
"""

import pytest

from labthings import fields, schema
from labthings.actions.thread import ActionThread
from labthings.extensions import BaseExtension
from labthings.views import ActionView, PropertyView, EventView
from marshmallow import validate
from apispec.utils import validate_spec

def test_openapi(thing):
    """Make an example Thing and check its openapi description validates"""
    class TestAction(ActionView):
        args = {"n": fields.Integer()}
        def post(self):
            return "POST"
    thing.add_view(TestAction, "TestAction")

    class TestProperty(PropertyView):
        schema = {"count": fields.Integer()}
        def get(self):
            return 1
        def post(self, args):
            pass
    thing.add_view(TestProperty, "TestProperty")

    class TestFieldProperty(PropertyView):
        schema = fields.String(validate=validate.OneOf(["one", "two"]))
        def get(self):
            return "one"
        def post(self, args):
            pass
    thing.add_view(TestFieldProperty, "TestFieldProperty")
    
    
    thing.spec.to_yaml()
    validate_spec(thing.spec)