from gevent.monkey import patch_all

__all__ = ["patch_all"]

"""
NOTE: THIS FILE IS EXCLUDED FROM OUR UNIT TESTS.

MONKEY PATCHING IN THE MIDDLE OF A TEST SUITE RUNNING
MAY CAUSE PROBLEMS.

GIVEN THAT THIS MODULE IS SIMPLY A PROXY FOR GEVENTS
MONKEY PATCHER, TESTSING IS FAIRLY REDUNDANT ANYWAY.

THIS SHOULD BE PERIODICALLY REVISITED TO MAKE SURE ITS
STILL TRUE.

THANKS
"""
